### ISSUE TITLE
./uploads error

### ISSUE THREAD

**Issue by ShakeelPK** [ciso360ai/ciso360ai#22]
Hi after run docker-compose up -d in my ubuntu20.04 lts. I'm facing this error in my docker status.

Please checkout and let me know how I can fix this issues thanks.

![Screenshot 2023-08-28 at 12 35 24 AM](https://github.com/ciso360ai/ciso360ai/assets/83941561/3a4c2c14-dbef-4f52-85c8-42f0b6990d26)

**Comment by ShakeelPK** [comment]
docker compose build also not working its show this error
![Screenshot 2023-08-28 at 1 23 12 AM](https://github.com/ciso360ai/ciso360ai/assets/83941561/fb1b3744-9e62-4915-a256-d596e53dfe33)

**Comment by ShakeelPK** [comment]
Afer add ./upload folder under api now its give me this error "Go" version I believe can you please tell me how to fix this error.
![Screenshot 2023-08-28 at 1 59 59 AM](https://github.com/ciso360ai/ciso360ai/assets/83941561/69aa2a28-f8a5-4ad9-9f95-fd6c0dc2195b)

**Comment by faustro** [comment]
Thanks for the report. Both issues have been fixed in the last update
Update your local repo, rebuild and test again
